### ISSUE TITLE
no posts are showing up

### ISSUE THREAD

**Issue by oxxz** [bitbrain/jekyll-dash#23]
first of all, im pretty new to jekyll. i've played around with it the last couple of days. i tried to install this theme, but no posts are showing up. i did a made a new fresh site with the default theme just to make sure nothing was wrong from my side - and the (first original) post shows up, then i install the theme, and i see "no posts yet.". as this was a new install im sure i didnt change anything to make them disappear, but do i need to make any change for them to show? i also want to add that the post is in the _site-folder, which makes it even more strange in my eyes.

this is on my computer, but im gonna use it on my vps when i get it working. so its not on github pages, if that does matter

**Comment by bitbrain** [comment]
Thanks for reporting this @oxxz - can you maybe push your code at least to a branch on https://github.com/oxxz/oddz.github.io? I need to take a look otherwise I don't know what the problem might be.

Thank you!

**Comment by oxxz** [comment]
@bitbrain now i've pushed the files to (https://github.com/oxxz/jekyll)

**Comment by bitbrain** [comment]
@oxxz I have taken a look at the files you have pushed. [jekyll-dash](https://github.com/bitbrain/jekyll-dash) by default is using [jekyll-paginate](https://jekyllrb.com/docs/pagination/) in order to display posts.

I have noticed that your [_config.yml](https://github.com/oxxz/jekyll/blob/master/_config.yml) is missing essential configuration, as described on the [README](https://github.com/bitbrain/jekyll-dash#configuration).

Can you please confirm that this indeed solves the issue you are having?

**Comment by oxxz** [comment]
@bitbrain yes, i did that before i tried a clean jekyll page, but i maybe forgot to put it in the gemfile before (stupid me). well, now i did add it both to the [gemfile](Gemfile) and [_config.yml](https://github.com/oxxz/jekyll/commit/fdba1c61d63187389ef7b9abfad486765ce555dd#diff-aeb42283af8ef8e9da40ededd3ae2ab2), but now i get `Pagination: Pagination is enabled, but I couldn't find an index.html page to use as the pagination template. Skipping pagination.`

**Comment by bitbrain** [comment]
@oxxz hah, according to [the official paginate documentation](https://jekyllrb.com/docs/pagination/):

> Pagination does not work from within Markdown files from your Jekyll site. Pagination works when called from within the HTML file, named index.html, which optionally may reside in and produce pagination from within a subdirectory, via the paginate_path configuration value.

That's not quite obvious initially. I am gonna add this to the theme readme as well.

Simply renaming your index.md into index.html should do the job.

**Comment by oxxz** [comment]
@bitbrain lol, thats so obvious. i tried to make an index.html, but didnt really knew what to put in it, but of course i should've just renamned the md file. thanks for your patience and your awesome looking theme! :)
