### ISSUE TITLE
Adding tags causes errors.

### ISSUE THREAD

**Issue by Zanark** [bitbrain/jekyll-dash#26]
When I run jekyll serve localy, I get the following error:

```
  Liquid Exception: no implicit conversion of nil into String in /_layouts/post.html
jekyll 3.8.5 | Error:  no implicit conversion of nil into String
```
I do not know much about ruby, but after some googling I found that something needs to be converted to a string, however I do not know what.

The header variables I assigned to a post are:

```
---
layout: "post"
title: "A Programmer stuck in a rut"
author: "Zanark"
tags : Tips
---
```

Can you please help me out with this, I am unable to find a solution for this.

*The code in /_layouts/post.html is exactly the same as the one in the repository on `master branch`*

**Comment by Zanark** [comment]
Solution: randomly typecasted some strings and the issue got resolved.

**Comment by bitbrain** [comment]
Interesting. @Zanark if you find a way to prevent this issue from happening for other people using the theme, feel free to create a PR!

**Comment by Zanark** [comment]
Yep, I'll try to find a better solution for this issue and will then send a PR.

P.S. Your theme is AWESOME!! :heart: it!!
