### ISSUE TITLE
Page build warning

### ISSUE THREAD

**Issue by sercangezer** [bitbrain/jekyll-dash#41]
Hi,

I have problem when I push to master branch. Please help me!
Thanks

`The page build completed successfully, but returned the following warning for the `master` branch:

You are attempting to use a Jekyll theme, "jekyll-dash", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://help.github.com/en/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-using-jekyll.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds`

**Comment by bitbrain** [comment]
Unfortunately, Github only allows certain plugins: https://github.com/bitbrain/jekyll-dash/blob/master/README.md#using-this-theme-directly-on-github-pages

In order to use this theme on github pages, either copy-paste the html directly or use a two repository approach, as described in the link.
