### ISSUE TITLE
can't install jekyll-dash with jekyll 4.1.1

### ISSUE THREAD

**Issue by hatsat32** [bitbrain/jekyll-dash#42]
Hi.

I have some issues with installing `jekyll-dash`. I create new fresh blog using `jekyll new something`. After that I try to add `gem "jekyll-dash"` to my gemfile. Then I try to run this command `bundle`. But gives me errors.

```
$ bundle
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In snapshot (Gemfile.lock):
    jekyll (= 4.1.1)

  In Gemfile:
    jekyll (~> 4.1.1)

    jekyll-dash was resolved to 1.3.4, which depends on
      jekyll (~> 3.5)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

I tried `bundle update` and some google stuff but did not work. I can't continue installation. any help would be great.

My System:
* jekyll 4.1.1
* ubuntu 20.04
* Bundler version 2.1.4
* ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

**Comment by bitbrain** [comment]
Thank you for reporting this. I am going to have a look at this.

**Comment by bitbrain** [comment]
@hatsat32 Github pages [is still on Jekyll 3.8](https://pages.github.com/versions/) so I cannot just "upgrade" the theme to 4.x

I might start another branch that works on 4.x upwards and build a separate gem for it (jekyll-dash version 2.x)

**Comment by bitbrain** [comment]
@hatsat32 I have crafted [a new 2.0.0 version of this theme to rubygems](https://rubygems.org/gems/jekyll-dash) 🛠. Feel free to add this to your Gemfile:
```ruby
gem 'jekyll-dash', '~> 2.0.0'
```
Keep in mind that if you are building your website directly through the Github Jekyll generator this will not work since gh-pages only runs on Jekyll 3.8.

Let me know on this ticket if it resolves the issue. Cheers! 🍻

**Comment by hatsat32** [comment]
Hi @bitbrain . It works great now.

I use gitlab pages. Gitlab uses docker container to build jekyll site. That is why I can use any extension and verison of jekyll. So I tried to upgrade jekyll version of my blog. when upgrading I face the error above. Anyway version 2.x works great now.

Thank you and have a nice day :)
