### ISSUE TITLE
New avatar source: urlpath

### ISSUE THREAD

**Issue by kodumulo** [bitbrain/jekyll-dash#48]
Can I use it like Avatar1.png in Dark Theme and Avatar2.png in Light Theme?
Oh, and the automatic distribution of the blog I asked last time worked well
Thanks :D

**Comment by bitbrain** [comment]
@kodumulo interesting idea. Can you give an example of why you would like to do this? In case you wanna keep the contrast ratio / adapt the image to the dark/light theme respectively, [we could do some CSS tricks with filters](https://www.w3schools.com/howto/howto_css_image_effects.asp).

**Comment by kodumulo** [comment]
@bitbrain 
I don't want to use css. If you look at my repository https://github.com/kodumulo/blog/tree/master/assets, you can see avator_dark.png and avator_light.png. I want the image to change because I designed it separately to match the dark and light themes.

**Comment by bitbrain** [comment]
@kodumulo I thought about it and renamed this ticket to create a new avatar source `urlpath` that should allow configuring URLs for `default` and `light` respectively.
