### ISSUE TITLE
 I can't integrate telegram

### ISSUE THREAD

**Issue by coffstation** [bitbrain/jekyll-dash#49]
@bitbrain I cannot embed the telegram comments for the website. Not shown in any way .. some ideas? :pensive:

This is the code: 

```html
<script 
async src="https://comments.app/js/widget.js?3" 
data-comments-app-website="code-widget"
data-limit="40" 
data-color="F95C54" 
data-outlined="1" 
data-colorful="1" 
data-dark="1">
</script>
```

**Comment by bitbrain** [comment]
I have not used telegram before, however, for Disqus, I assume it is similar:

- have you listed your github URL on the comments app? If the URL signature does not match it will fail
- worth checking for JS errors in the console?

**Comment by bitbrain** [comment]
@coffstation any update on this?

**Comment by bitbrain** [comment]
Closing this for now.
