### ISSUE TITLE
How to change permalink?

### ISSUE THREAD

**Issue by risspect** [bitbrain/jekyll-dash#50]
I've tried to change and then i've no result
I edit in `_config.yml` at `tag_permalink_style: pretty` to `tag_permalink_style: none`

**Comment by bitbrain** [comment]
Hey @risspect,

that property is [specifically](https://github.com/pattex/jekyll-tagging#pretty-page-links-) for the `jekyll-tagging` plugin. For setting permalinks in Jekyll, [read up here](https://jekyllrb.com/docs/permalinks/), e.g.:
```yaml
permalink: /:categories/:year/:month/:day/:title:output_ext
```
