### ISSUE TITLE
Wierd bug, fails to build a post with specific name

### ISSUE THREAD

**Issue by VedantParanjape** [bitbrain/jekyll-dash#54]
This is the repository: https://github.com/SRA-VJTI/sra-vjti.github.io/

Whenever I push with the following file name: `2020-12-11-singularity-ros-melodic.md` (in /_posts), then the github actions build will generate this page, if I rename it to `2020-12-12-singularity-ros-melodic`, it fails to generate this page and commit to gh-pages.

Tested it locally using `bundle exec jekyll serve` works fine

**Comment by bitbrain** [comment]
This might be expected because Jekyll needs to know the file format. Omitting `.md` lets Jekyll confused because it doesn't know if it should interpret it as either HTML or Markdown.

Read more about it here: https://jekyllrb.com/docs/posts/

**Comment by VedantParanjape** [comment]
> This might be expected because Jekyll needs to know the file format. Omitting `.md` lets Jekyll confused because it doesn't know if it should interpret it as either HTML or Markdown.
> 
> Read more about it here: https://jekyllrb.com/docs/posts/

Sorry it was a typo, The final file name had .md in it.
