### ISSUE TITLE
wierd bug, page build fails on naming it with specific name

### ISSUE THREAD

**Issue by VedantParanjape** [bitbrain/jekyll-dash#56]
This is the repository: https://github.com/SRA-VJTI/sra-vjti.github.io/

Whenever I push with the following file name: `2020-12-11-singularity-ros-melodic.md` (in /_posts), then the github actions build will generate this page, if I rename it to `2020-12-12-singularity-ros-melodic.md`, it fails to generate this page and commit to gh-pages.

Tested it locally using `bundle exec jekyll serve` works fine

**Comment by bitbrain** [comment]
Is there any error message? What does it say? Or does it fail silently?

**Comment by VedantParanjape** [comment]
> Is there any error message? What does it say? Or does it fail silently?

It doesn't fail, that page simply isn't generated.

**Comment by bitbrain** [comment]
This sounds like a Jekyll issue to me, rather than an issue with this theme. Please raise this with the Jekyll community!
