### ISSUE TITLE
Open images in a new tab on click

### ISSUE THREAD

**Issue by theamanrawat** [bitbrain/jekyll-dash#57]
Hi, Its better to make images openable on click 

If we have one image in our blog and we want it to be open in full screen when we click on it so it would be better for user to view image clearly.

Thank you

**Comment by bitbrain** [comment]
Great suggestion!

**Comment by theamanrawat** [comment]
https://theamanrawat.github.io

I added this in my blog. You can check this and If you want me to make pull request then I can make a pull request.

**Comment by bitbrain** [comment]
@theamanrawat looks dope - my only feedback: the cursor should change when hovering an image so users know they can click it.

**Comment by theamanrawat** [comment]
>the cursor should change when hovering an image so users know they can click it

Great. I'll add this and
