### ISSUE TITLE
How to Add Tags ?

### ISSUE THREAD

**Issue by 0xM00D** [bitbrain/jekyll-dash#68]
Hi there !
why tags don't appere in my page ?

**Comment by ck-pro** [comment]
@0xM00D - Presuming you're using GitHub Pages, this might help you understand why tags aren't visible. 
https://github.com/bitbrain/jekyll-dash#using-this-theme-directly-on-github-pages

**Comment by bitbrain** [comment]
I am closing this as it is a limitation to github pages. Read the link @ck-pro posted for details how to make them visible.
