### ISSUE TITLE
Tags are not visible on hosting

### ISSUE THREAD

**Issue by Xan0er** [bitbrain/jekyll-dash#69]
Can you please help me with the tags? I am not able to figure out that how to make tags visible.

**Comment by ck-pro** [comment]
Presuming you're using GitHub Pages, this might help you understand why tags aren't visible. 
https://github.com/bitbrain/jekyll-dash#using-this-theme-directly-on-github-pages

**Comment by bitbrain** [comment]
Closing this, as it is described in the README how to make tags visible.
