### ISSUE TITLE
Bug about fonts scss

### ISSUE THREAD

**Issue by FavorMylikes** [bitbrain/jekyll-dash#71]
```scss
@include font('Varela Round', '/assets/fonts/VarelaRound-Regular');
```

Seems here need a `subpath` to config it

**Comment by FavorMylikes** [comment]
link here 

https://github.com/bitbrain/jekyll-dash/blob/caec02733516afea7d7740ea729b19970438f324/_sass/dash/_fonts.scss#L15

**Comment by bitbrain** [comment]
Could you raise a PR?

**Comment by bitbrain** [comment]
@FavorMylikes what is the exact bug here?

**Comment by bitbrain** [comment]
Closing this for now.
